### ISSUE TITLE
Use declaration files for TypeScript types (instead of source code)

### ISSUE THREAD

**Issue by OliverJAsh** [paularmstrong/build-tracker#105]
The `types` field in the `package.json` of `@build-tracker/plugin-with-postgres` currently refers to the TS _source code_:

https://github.com/paularmstrong/build-tracker/blob/f66274bba0003e58cd2922b759cc883222e21ac9/plugins/with-postgres/package.json#L10

This means that TS users who import from this module will get lots of errors relating to the source code.

It would be better if the `types` field instead just referred to some declaration files (`.d.ts`). These could be generated using the `declaration` compiler option. This way, users will only import the types—they won't be forced to type check the actual source code itself.

I'm happy to raise a PR if that sounds good to you?

**Comment by paularmstrong** [comment]
> This means that TS users who import from this module will get lots of errors relating to the source code.

Why is that? The source code should not have errors.

**Comment by OliverJAsh** [comment]
I didn't look too hard, just because it's unusual for consumers to type check the source code of the library they are using, so I thought I'd suggest just fixing that instead.

One thing I did notice though: it looked like some dependencies were missing types such as `express`. `@types/express` is a dev dependency, so consumers won't install this: https://github.com/paularmstrong/build-tracker/blob/f66274bba0003e58cd2922b759cc883222e21ac9/src/server/package.json#L36.

**Comment by paularmstrong** [comment]
My biggest concern is that moving to declaration files means that dev mode in the monorepo will start throwing type errors unless they are rebuilt on every file change.

A solution will probably be needed to rewrite package.json files before and after publishing so that the value is set to declaration when publishing, but the source files otherwise.

**Comment by OliverJAsh** [comment]
> Unless typescript has a way to watch and always rebuild declaration files.

We can use the `watch` and `declaration` compiler options in tandem, or do I misunderstand? E.g. `tsc --watch --declaration`, or the same config inside `tsconfig.json`.

**Comment by paularmstrong** [comment]
That requires running that in tandem as a separate process at all times though, right?

**Comment by OliverJAsh** [comment]
Hmm yeah, that's right.

I wonder if the `types` field should be used in development at all. ([The docs](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) only suggest using it with declaration files.) Perhaps it should always point to the declaration files. Then, the `main` field will point to the compiled code, except for in dev, when the `main` field will point to the TS source code instead of the compiled code. That must be a common/solved problem in monorepos?

**Comment by paularmstrong** [comment]
For the monorepo I use at work, we have a whole build process that copies that `package.json` into the `dist` directory, rewrites a bunch of fields, then publishes from the `dist` directory. I suspect a lot of people have written similar tooling.

**Comment by OliverJAsh** [comment]
> My biggest concern is that moving to declaration files means that dev mode in the monorepo will start throwing type errors unless they are rebuilt on every file change.

I tested this (https://github.com/paularmstrong/build-tracker/pull/117) and it doesn't seem to be a problem. VS Code doesn't use `types` if the source code it's importing is in TS—and it does seem to be importing the TS file. Steps to test this (when running https://github.com/paularmstrong/build-tracker/pull/117):

1. Opened `src/app/src/views/AppBar.tsx`.
2. Navigated to definition of `ArtifactRow` (in `src/comparator/src/index.ts`) via first import
3. Delete the type

`AppBar` immediately starts to throw compile errors—we do not have to recompile.

@paularmstrong If that sounds good to you, I'll go ahead and update all other `package.json`s.
