### ISSUE TITLE
Error when uploading/creating build inside Travis job

### ISSUE THREAD

**Issue by OliverJAsh** [paularmstrong/build-tracker#106]
Thanks again for this fantastic library. I hope my issues are helpful…

I'm filing this issue to help others who might run into the same thing when using Travis. (Perhaps we could add something to the docs?) I've found and noted a fix, so I'll close this immediately.

When I ran `bt-cli upload-build` inside of a [Travis](https://travis-ci.com/) job, I got an error:

```
$ bt-cli upload-build
Usage: bt-cli upload-build
Create a build
  --branch, -b        Set the branch name and do not attempt to read from git  [string]
  --config, -c        Override path to the build-tracker CLI config file  [string]
  --skip-dirty-check  Skip the git work tree state check  [boolean] [default: false]
Global:
  --help, -h  Show this help screen  [boolean]
  --verbose
Options:
  --version  Show version number  [boolean]
  -v         Set the logging verbosity. Use -vv for more verbose  [count] [default: 0]
{
  code: 128,
  stderr: 'fatal: Not a valid object name origin/master\n',
  errors: { spawn: null, stdout: null, stderr: null }
}
```

This might have something to do with `defaultBranch`:

https://github.com/paularmstrong/build-tracker/blob/f66274bba0003e58cd2922b759cc883222e21ac9/src/cli/src/commands/create-build.ts#L82

https://github.com/paularmstrong/build-tracker/blob/f66274bba0003e58cd2922b759cc883222e21ac9/src/cli/src/modules/git.ts#L14

I suspect `origin/master` doesn't exist because of the way Travis clones the Git repo: [it only creates a shallow clone](https://docs.travis-ci.com/user/customizing-the-build#git-clone-depth).

I was able to fix this issue by [disabling the shallow clone](https://docs.travis-ci.com/user/customizing-the-build#git-clone-depth). In `.travis.yml`:

```yml
git:
  depth: false
```

**Comment by paularmstrong** [comment]
@OliverJAsh did you close this after seeing:
>   --branch, -b        Set the branch name and do not attempt to read from git  [string]

I added that some time back because we have the same issue with our internal Jenkins setup

**Comment by OliverJAsh** [comment]
I don't think the branch flag would have helped in this case, because this has to do with the "default branch" rather than the "current branch". In my test, the Travis build is for a branch named `feature` yet the error message is concerning `origin/master`.

I closed the issue after I was able to workaround it by telling Travis to do a full clone (as described above).

**Comment by paularmstrong** [comment]
Oh interesting. That may have to do with the [create-build process](https://github.com/paularmstrong/build-tracker/blob/next/src/cli/src/commands/create-build.ts#L88) looking for the `--parent-revision` (which you can supply). This SHA is saved to the database with the build so that it is more accurate describing the changes (removing conflicts between commits on separate parts of the git tree).

The full checkout may be a good thing to add to the continuous integration guides in the docs. Maybe even a section for "Using with Travis CI"

**Comment by paulirish** [comment]
I went with [`git fetch deepen=100`](https://github.com/GoogleChrome/lighthouse/pull/10550/commits/5993df8579c8407565e1a42c2389c2e3bae56078) after my other tests and before build-tracker. 

I didn't benchmark things though.. It's very possible doing a full clone at the start would be equivalent.
