### ISSUE TITLE
POST /api/builds responds with 404

### ISSUE THREAD

**Issue by OliverJAsh** [paularmstrong/build-tracker#107]
# Problem

A short explanation of your problem or use-case is helpful!

**Steps to Reproduce:**

1. With a fresh database, run `bt-cli upload-build`

**Expected Result**

200 response

**Actual Result**

404 response

![image](https://user-images.githubusercontent.com/921609/74454400-bd2cdf80-4e7b-11ea-8d6e-99534a82f378.png)

This seems to happen as a result of `queries.byRevision(build.getMetaValue('parentRevision'))`. In this case, it seems that there is no build for the parent revision, because this is the first time a build has been uploaded.

When there is no parent for the "parent revision", perhaps we should still respond with a 200? WDYT?

**Comment by paularmstrong** [comment]
I hadn't put a ton of thought into it, to be honest. It might be best to catch the error on looking up the parentRevision, continue building the comparator, and give a full response.

The one thing that we need to catch in some way, though is the case where, _after the initial build_, the parentRevision is not found.

**Comment by OliverJAsh** [comment]
> continue building the comparator, and give a full response.

That's what I thought. Is it possible to build a comparator with just one build? I'm happy to send a PR.

(Thanks again for your work on this. I love this project!)

**Comment by paularmstrong** [comment]
Yep! `Comparator` accepts any number of builds greater than zero

**Comment by OliverJAsh** [comment]
#110
