### ISSUE TITLE
Add message when there are no builds to show

### ISSUE THREAD

**Issue by paularmstrong** [paularmstrong/build-tracker#128]
# Problem

The default view when first deploying the application results in a blank screen. It's unclear what is happening.

<img width="1392" alt="Screen Shot 2020-02-17 at 1 58 07 PM" src="https://user-images.githubusercontent.com/33297/74688781-962d2100-518d-11ea-9216-2f09d448f4b5.png">

# Solution

* A message that the data set is empty
* A link to documentation for help

**Comment by montogeek** [comment]
Isn't it better to show an explicit message saying: "Please add at least 2 builds to show a comparison"?

**Comment by paularmstrong** [comment]
Definitely. At the moment, there's a lack of context for why there are no builds to be able to show. This state can be brought up if there are errors in the XHR or if the selected date range just happens to not have anything in it. More contextual awareness will be needed to have different messages for different states.
