### ISSUE TITLE
Indicate unexpected hash changes in Markdown table

### ISSUE THREAD

**Issue by OliverJAsh** [paularmstrong/build-tracker#151]
# Problem

In you inspect [this build comparison](https://unsplash-web-build-tracker.herokuapp.com/builds/c98c0fd1da8cac603b42c918cb8be70deb1b7e81/94334b2697dd7787e7b285ad6e07c10888840658?sizeKey=gzip&disabledArtifactsVisible=true&graphType=STACKED_BAR&comparedRevisions=c98c0fd1da8cac603b42c918cb8be70deb1b7e81&comparedRevisions=94334b2697dd7787e7b285ad6e07c10888840658), you will see that several artifacts have unexpected hash changes. This is clearly indicated in the UI:

![image](https://user-images.githubusercontent.com/921609/75457878-f170c780-5974-11ea-884a-093d35dad251.png)

Here is the same comparison in the form of a Markdown table (after using an artifact filter to remove rows that didn't change). As you can see, many rows are included but the table doesn't make it clear why they are included. We can see from the UI that they are included because of unexpected hash changes, or because there was a delta but it was too insignificant for any difference to be visible when viewed in KiBs.

|                                                                                                               |    30607b0 |    0a7b976 |              Δ1 |
| :------------------------------------------------------------------------------------------------------------ | ---------: | ---------: | --------------: |
| All                                                                                                           | 935.24 KiB | 936.17 KiB | 0.93 KiB (0.1%) |
| vendors~main                                                                                                  | 229.32 KiB |  230.2 KiB | 0.88 KiB (0.4%) |
| main                                                                                                          |  89.34 KiB |  89.33 KiB |  -0 KiB (-0.0%) |
| explore-old-route                                                                                             |  59.95 KiB |  59.95 KiB |    0 KiB (0.0%) |
| user-stats-sub-route                                                                                          |  19.31 KiB |  19.31 KiB |    0 KiB (0.0%) |
| uploader                                                                                                      |  15.55 KiB |   15.6 KiB | 0.05 KiB (0.3%) |
| photos-route                                                                                                  |  15.54 KiB |  15.54 KiB |  -0 KiB (-0.0%) |
| collection-route~editorial-route~explore-route~following-route~photos-route~search-photos-route~topi~50ad0392 |  12.23 KiB |  12.23 KiB |    0 KiB (0.0%) |
| user-route                                                                                                    |  11.36 KiB |  11.36 KiB |    0 KiB (0.0%) |
| collection-route                                                                                              |  11.31 KiB |  11.31 KiB |    0 KiB (0.0%) |
| edit-modal                                                                                                    |   9.01 KiB |   9.01 KiB |  -0 KiB (-0.0%) |
| editorial-route                                                                                               |   8.47 KiB |   8.47 KiB |    0 KiB (0.0%) |
| campaign-proposal-route                                                                                       |   7.85 KiB |   7.85 KiB |    0 KiB (0.0%) |
| explore-route                                                                                                 |   7.34 KiB |   7.35 KiB |    0 KiB (0.0%) |
| following-route                                                                                               |   6.11 KiB |   6.11 KiB |    0 KiB (0.0%) |
| explore-route~topics-route                                                                                    |   5.57 KiB |   5.57 KiB |    0 KiB (0.0%) |
| collections-feed-route                                                                                        |   5.27 KiB |   5.27 KiB |    0 KiB (0.0%) |
| search-photos-route                                                                                           |   5.01 KiB |   5.01 KiB |    0 KiB (0.0%) |
| collection-route~photos-route~user-feed-sub-route                                                             |   4.32 KiB |   4.32 KiB |    0 KiB (0.0%) |
| search-collections-route                                                                                      |   3.88 KiB |   3.89 KiB |    0 KiB (0.0%) |
| feed                                                                                                          |   1.34 KiB |   1.34 KiB |    0 KiB (0.0%) |

# Solution

Add some sort of indication to rows in the Markdown table which are included because of unexpected hash changes.

**Comment by paularmstrong** [comment]
This is a great suggestion. It should be fairly trivial to add, as each `DeltaCell` has a `hashChanged: boolean` property, so it can be part of the string formatter.

Since we're on the subject, I'd actually like a different emoji to represent this than reusing the ⚠️  that's used for budget warnings. Any suggestions?

**Comment by OliverJAsh** [comment]
#️⃣, haha? I'm not very creative with emojis unfortunately

**Comment by paularmstrong** [comment]
#️⃣is probably clearest
