### ISSUE TITLE
Error: [object Object]

### ISSUE THREAD

**Issue by paulirish** [paularmstrong/build-tracker#176]
# Problem

I got this locally when I was first setting up things... But surprisingly this repo's GH actions ran into it:  https://github.com/paularmstrong/build-tracker/pull/175/checks?check_run_id=518328757

![image](https://user-images.githubusercontent.com/39191/77030968-77bd6f80-695d-11ea-87cb-fb7f841a4cf2.png)

**Steps to Reproduce:**

Pretty sure if you don't set the BT_API_AUTH_TOKEN env var then the server will 401 and this'll happen. (That's how I ran into it).

Probably should stringify if its an object?

**Comment by paularmstrong** [comment]
Ahhh, so that's what it is :) We can definitely fix that over at [paularmstrong/build-tracker-action](https://github.com/paularmstrong/build-tracker-action)

I've noticed that the GH action doesn't include secrets when it's run for PRs from forks of a repo. Searching around the forums, people have been complaining about it since actions were introduced :(

**Comment by paulirish** [comment]
> Ahhh, so that's what it is :) We can definitely fix that over at [paularmstrong/build-tracker-action](https://github.com/paularmstrong/build-tracker-action)

Hmmm. I haven't used the gh action at all yet, fwiw.
This was just between my heroku instance and the CLI (that i globally installed with npm)

To get visibility I added a `console.log({response});` right here:
https://github.com/paularmstrong/build-tracker/blob/4c4e5e89c5bc237ed1fffb96864ac853b3f1a6c8/src/api-client/src/modules/upload-build.ts#L55

---------

> I've noticed that the GH action doesn't include secrets when it's run for PRs from forks of a repo. Searching around the forums, people have been complaining about it since actions were introduced :(

Yup. We ran into that with the lighthouse github action too. its frustrating, but from a security POV i totally get it.
