### ISSUE TITLE
Silent failure when `BT_API_AUTH_TOKEN` wasn't provided

### ISSUE THREAD

**Issue by paulirish** [paularmstrong/build-tracker#177]
(just breaking this piece of #176 into a diff issue)

# Problem

New users are dumb. Like me. 

And when I first tried upload-build i hadn't yet set the env variable. The server 401'd (and that was a silentish failure thanks to #176). But it took a minute to realize I hadn't included `BT_API_AUTH_TOKEN`.

Your [CLI docs](https://buildtracker.dev/docs/packages/cli#upload-build) already include this env var, but I hadn't yet found those docs. :)

# Idea

Perhaps a friendly error message could be provided? Something a la..

> The server returned a 401 Unauthorized Error. Did you include the correct BT_API_AUTH_TOKEN?

--------

also wow the docs are really nice. docusaurus seems badass.

**Comment by paularmstrong** [comment]
I love the idea of including more information in the error responses. Will look into this tonight.
