### ISSUE TITLE
Not a valid object name origin/master

### ISSUE THREAD

**Issue by paulirish** [paularmstrong/build-tracker#195]
## Problem

Getting buildtracker setup for the lighthouse repo. 

Here's the workflow: https://github.com/GoogleChrome/lighthouse/blob/buildtracker/.github/workflows/basics.yml

Here's a run of it: https://github.com/GoogleChrome/lighthouse/pull/10550/checks?check_run_id=575190581

## Steps to Reproduce

Not sure. This is a basic boring PR from a separate branch into master. Same remote.

## Expected Result

I expect it wouldn't have errored 

## Actual Result

`upload-build` fails with `
{ code: 128,
  stderr: 'fatal: Not a valid object name origin/master\n',
  errors: { spawn: null, stdout: null, stderr: null } }`

I ran with `-vv` but it doesnt help much. No stacktrace or hint on the `git` call that returned this error.

**Comment by OliverJAsh** [comment]
@paulirish I also ran into this: https://github.com/paularmstrong/build-tracker/issues/106

> I was able to workaround it by telling Travis to do a full clone (as described above).

https://github.com/paularmstrong/build-tracker/issues/106#issuecomment-584329026
