### ISSUE TITLE
Avoid setting "Revision" as PRIMARY_KEY

### ISSUE THREAD

**Issue by PranaytheSingh** [paularmstrong/build-tracker#210]
## Problem

The database plugins are setup with setting revision key as the PRIMARY_KEY. However if we re-run the build tracker job it ends up in a duplicate key error ( Since the sha is the same). 

## Proposed solution

I'm proposing adding a unique ID key to each row which will have the property of Uniq and Primary Key. This way subsequent re-runs will ensure that the job works even the sha is unchanges.

**Comment by paularmstrong** [comment]
Discussed in person. We'll be implementing a `getBuild()` method in the `@build-tracker/api-client` to allow checking for existing builds to avoid attempting to double-post.
