### ISSUE TITLE
Disappearing graph on mouseover

### ISSUE THREAD

**Issue by paulirish** [paularmstrong/build-tracker#216]
## Problem

In some cases, when I start interacting with the graph, the whole thing disappears. I also then see an exception in the console.

example exception: ` Uncaught TypeError: Cannot read property '249' of undefined`

## Steps to Reproduce

1. load https://lh-build-tracker.herokuapp.com/builds/limit/300
2. move your mouse inside the graph
   - i think the repro is probably... your mouse cursor has to enter into the graph from the top (where there's nothing plotted).

## Expected Result

it works

## Actual Result

exception.

i debugged a tad and it looks to be dying here: 

https://github.com/paularmstrong/build-tracker/blob/1d45c702be4fecaf75ffa239de5f70cdb9823691/src/app/src/components/Graph/HoverOverlay.tsx#L114-L115

`dataSeries` is undefined... because, in this case, `hoveredArtifact` is an empty string.
also it's true the mouse wasn't hovering on anything just yet.

**Comment by OliverJAsh** [comment]
I think this has just been fixed! https://github.com/paularmstrong/build-tracker/issues/215#event-4202143586

**Comment by OliverJAsh** [comment]
P.S. this bug would have been caught by the compiler with the new TS flag: `noUncheckedIndexedAccess`.

**Comment by paularmstrong** [comment]
> I think this has just been fixed! [#215 (comment)](https://github.com/paularmstrong/build-tracker/issues/215#event-4202143586)

I can repro on the main branch. Looking into it now.

**Comment by paularmstrong** [comment]
> i think the repro is probably... your mouse cursor has to enter into the graph from the top (where there's nothing plotted).

Confirmed, the issue is that when hovering whitespace, there's no hovered artifact, so it's blipping out trying to figure out where in the data series to get the information from
