### ISSUE TITLE
featuring build-tracker in Docusaurus

### ISSUE THREAD

**Issue by nickbui729** [paularmstrong/build-tracker#54]
Hello, we would like to feature your project to the Docusaurus [users](https://docusaurus.io/en/users) 

If you are okay with it, are you able to provide a logo we can use? Additional information can be found [here](https://github.com/facebook/Docusaurus/issues/1437)

**Comment by paularmstrong** [comment]
@nickbui729 Can you please hold off until May 23rd? I haven't officially released the current build yet and don't want to lead people down the wrong path.

**Comment by nickbui729** [comment]
Yes sounds good, will get back to you next week!

**Comment by paularmstrong** [comment]
@nickbui729 All good to go! Still in alpha release, but I've been speaking publicly about it.
