### ISSUE TITLE
Safari refuses to load scripts

### ISSUE THREAD

**Issue by Haroenv** [paularmstrong/build-tracker#56]
# Problem

In Safari (I'm using Tech Preview Release 81 (Safari 12.2, WebKit 14608.1.19.5)) it seems like CSP is enforced more thoroughly, and some scripts are not allowed to be loaded

**Steps to Reproduce:**

1. open demo in safari

2. click on a place on the graph

**Expected Result**

Here's what I expect to see when I run the above:

a new item being added to the comparison list

**Actual Result**

Here's what I _actually_ see when I run the above:

<img width="1019" alt="Screenshot 2019-05-23 at 16 39 08" src="https://user-images.githubusercontent.com/6270048/58261839-5d385b00-7d79-11e9-9b26-c78b90a0efb3.png">

**Comment by paularmstrong** [comment]
Whoa good catch! Looks like a CSP issue.

**Comment by Haroenv** [comment]
works now!
