### ISSUE TITLE
Cannot find module '@build-tracker/formatting'

### ISSUE THREAD

**Issue by mkaraula** [paularmstrong/build-tracker#58]
# Problem

I am trying to install the Build Tracker server following the steps in the documentation but when trying to run bt-server i am getting: 

```
Error: Cannot find module '@build-tracker/formatting'
```
**Steps to Reproduce:**

1. `npm install --save @build-tracker/server@latest`
2.  create `build-tracker.config.js` on project root with: 
```
module.exports = {
  url: 'https://my-url',
};
```
3. add `"start": "bt-server run"` to the scripts section of `package.json`
4. `npm start`

**Comment by paularmstrong** [comment]
Fixed in 8dfc827c1e9c50bce35d53930395dec08e8c7436
Will be out in next alpha release
