### ISSUE TITLE
docs/docs/installation.md for dummies

### ISSUE THREAD

**Issue by sesam** [paularmstrong/build-tracker#59]
Is the installation page WIP? It probably needs more words, or hints (links?) to where things are explained.

Specifically, reading the page, I still don't understand these three:

```
module.exports = {
  // TODO
};
```

`applicationUrl: 'https://your-build-tracker-app',
`

```
  // TODO
};

```

**Comment by paularmstrong** [comment]
Yeah those could use more info. It should be easy enough to pull the existing info from the other pages.
