### ISSUE TITLE
[blog]

### ISSUE THREAD

**Issue by sesam** [paularmstrong/build-tracker#61]
# Problem

The Blog section of the site is blank.

# Solution

Ideas:
- Invite a guest blogger to get things moving?
- Update existing first post to get some minimal meat. If the blog is RSS-fed anywhere, better to make new posts instead.
- Add a repost to point out the React Conf talk where this project is showcased. 
- Add a post showin some good twitter thread about this project. This might make the project showcase where its community is.

**Comment by paularmstrong** [comment]
I have some things in the works! I'll hopefully have at least something better up in the next week
