### ISSUE TITLE
[docs] Add optional best-practice starter?

### ISSUE THREAD

**Issue by sesam** [paularmstrong/build-tracker#62]
# Problem

To convert visitors to users (especially those coming here from React Europe 2019) they could be offered a sample project to clone and get all the goodies: husky doing eslint, pretty, lint-staged, etc. greenkeeper. snyk? yarn! tsconfig. README, maybe with a link to [RDD](https://medium.com/@liran.tal/a-suggested-approach-for-your-next-project-rdd-readme-driven-development-5fc64c7845db).

# Solution

It looks like this could basically be a copy of your existing build-tracker repo, trimmed down. 

Maybe a script could do more or less:
```
DIR=sample-$(date "+%Y-%m-%d_%H%M")
mkdir $DIR
cd $DIR
git init
git remote add sample-parent https://github.com/paularmstrong/build-tracker.git
git fetch --depth 1 sample-parent next
git merge sample-parent/next
git rm -r src/{comparator,fixtures,formatting,server}
# git rm ....... OK I should've picked some other repo as parent :)
```
So this would be the basic idea. Probably still keep lerna, to also let people get comfortable with monorepos and @package/separations without causing much developer-unhappiness

Do you have some favorite git repo sample that would be better to start from and add in build-tracker on top? Ideally a repo with all the user-specific fields written in commits on top of a git --depth 1 base, so the user can easily see and edit right in the first commits their project name etc. But stepwise, basic now is better than perfect ...someday.

**Comment by paularmstrong** [comment]
> get all the goodies: husky doing eslint, pretty, lint-staged, etc. greenkeeper. snyk? yarn! tsconfig. README

I think there's some confusion here. Build Tracker won't help you with the local development pieces from my talk at React Europe—only performance budgeting. Maybe I'm misreading the issue?

**Comment by sesam** [comment]
I muddled this. The suggestion is to provide an example repo and info how to use it as a starter. Mkdir, git init, git pull https://... is the shortest possible command list. I only took this repo as an example of one with all bells n whistles already setup. Got feedback from my colleagues they might prefer a starter without lerna, so I'll look a bit further for our needs.

**Comment by paularmstrong** [comment]
Okay, I think you're looking in the wrong place for a starter repo on these types of things.

**Comment by paularmstrong** [comment]
@sesam I created a github repo template here: https://github.com/paularmstrong/monorepo-ts

More info on templates: https://mobile.twitter.com/github/status/1136671651540738048
