### ISSUE TITLE
install docs show cli using build-tracker.config.js when it should be build-tracker-cli.config.js

### ISSUE THREAD

**Issue by jdmairs** [paularmstrong/build-tracker#98]
# Problem

Getting Started and CLI sections both say create a config file and name it build-tracker.config.js which is the server one not the cli one.

**Steps to Reproduce:**

1. 2.

3. ...

**Expected Result**

Here's what I expect to see when I run the above:

**Actual Result**

Here's what I _actually_ see when I run the above:

**Comment by paularmstrong** [comment]
The CLI is run in your application that you will be building and sending stats on to your build-tracker server.

The server config should be somewhere else.

**Comment by jdmairs** [comment]
Paul I understand that but the docs DO NOT say that...they reference the same config for both!
I didn't realize it was a different config until I looked in your demos folder.
The docs need updating.

**Comment by paularmstrong** [comment]
Cool. Create a PR if you'd like to updat eit.
