### ISSUE TITLE
npx bt-cli create-build gives TypeError: cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by jdmairs** [paularmstrong/build-tracker#99]
# Problem

Trying to upload a build.

**Steps to Reproduce:**

0. `npm run build (builds my webpack bundle in /dist/`

1. In one cmd prompt: npx bt-server run
```
{"level":30,"time":1574359053032,"pid":1239,"hostname":"johns-mbp.lan","msg":"Build Tracker server running on port 3000","v":1}
```

2. `npx bt-cli create-build`

**Expected Result**

I'm not sure...

It's not clear why the server and the client need a url to my app.  Should I be running an http-server so that my production build is served up?  The docs make it sound like the server is doing that..."Your application will now be accessible at the provided url."

**Actual Result**

Here's what I _actually_ see when I run the above:

```
TypeError: Cannot read property 'forEach' of undefined
    at Object.<anonymous> (/Users/johnmairs/Documents/gear/node_modules/@build-tracker/cli/dist/commands/stat-artifacts.js:75:31)
    at step (/Users/johnmairs/Documents/gear/node_modules/@build-tracker/cli/dist/commands/stat-artifacts.js:32:23)
    at Object.next (/Users/johnmairs/Documents/gear/node_modules/@build-tracker/cli/dist/commands/stat-artifacts.js:13:53)
    at fulfilled (/Users/johnmairs/Documents/gear/node_modules/@build-tracker/cli/dist/commands/stat-artifacts.js:4:58)
```

Here's the contents of my webpack dist folder

```
johnmairs@johns-mbp gear (213-addBuildTracker) $ ls dist/
1c8b268ec020a3aa5cd211cdda05fe2b.png	bundle.js.br				main.9847c6831b516c2e5a76.css.br
200b3fc810ff360a023c4cc309f77e5a.png	bundle.js.map				main.9847c6831b516c2e5a76.css.map
7a564d5604efdab6ca2325dcced48457.png	favicon.ico				mapTiles
995a1d96b1fef026c61ac03f4c6ff841.png	index.html				report.html
bundle.js				main.9847c6831b516c2e5a76.css
```

Here's my server config:

```
const withPostgres = require('@build-tracker/plugin-with-postgres').default;

module.exports = withPostgres({
  url: 'https://localhost:443',
  pg: omitted
});
```

Here's my client config?:

```
module.exports = {
  applicationUrl: 'https://localhost:443', // The same as your server config `url`
  artifacts: ['dist/**/*.js'], // an Array of glob-style file paths
};
```

**Comment by paularmstrong** [comment]
Per your other issue (#98), it looks like you are giving your server config to your cli. You can give them different names or place them in different folders and use the `--config` argument to give each a different location to look at. [docs here](https://buildtracker.dev/docs/cli#upload-build)

**Comment by jdmairs** [comment]
Actually I'm not.  I just updated my comment to show that.  Please reopen issue.

**Comment by paularmstrong** [comment]
This works absolutely fine in the demo application, so if you can debug and show that the problem is somewhere in the BT code and provide a PR, that would really help.
